/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link RewardDistributor}
 * @category Accounts
 * @category generated
 */
export type RewardDistributorArgs = {
  bump: number
  stakePool: web3.PublicKey
  authority: web3.PublicKey
  rewardMint: web3.PublicKey
  rewardAmount: beet.bignum
  rewardDurationSeconds: beet.bignum
  rewardsIssued: beet.bignum
  multiplierDecimals: number
}

export const rewardDistributorDiscriminator = [
  215, 10, 217, 199, 104, 194, 97, 227,
]
/**
 * Holds the data for the {@link RewardDistributor} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class RewardDistributor implements RewardDistributorArgs {
  private constructor(
    readonly bump: number,
    readonly stakePool: web3.PublicKey,
    readonly authority: web3.PublicKey,
    readonly rewardMint: web3.PublicKey,
    readonly rewardAmount: beet.bignum,
    readonly rewardDurationSeconds: beet.bignum,
    readonly rewardsIssued: beet.bignum,
    readonly multiplierDecimals: number
  ) {}

  /**
   * Creates a {@link RewardDistributor} instance from the provided args.
   */
  static fromArgs(args: RewardDistributorArgs) {
    return new RewardDistributor(
      args.bump,
      args.stakePool,
      args.authority,
      args.rewardMint,
      args.rewardAmount,
      args.rewardDurationSeconds,
      args.rewardsIssued,
      args.multiplierDecimals
    )
  }

  /**
   * Deserializes the {@link RewardDistributor} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [RewardDistributor, number] {
    return RewardDistributor.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link RewardDistributor} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<RewardDistributor> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find RewardDistributor account at ${address}`)
    }
    return RewardDistributor.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'DEvYCMc1BQ7uN3hHgdmHgiNQee2vydMdX3xg9ZJf42c8'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, rewardDistributorBeet)
  }

  /**
   * Deserializes the {@link RewardDistributor} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [RewardDistributor, number] {
    return rewardDistributorBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link RewardDistributor} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return rewardDistributorBeet.serialize({
      accountDiscriminator: rewardDistributorDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link RewardDistributor}
   */
  static get byteSize() {
    return rewardDistributorBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link RewardDistributor} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      RewardDistributor.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link RewardDistributor} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === RewardDistributor.byteSize
  }

  /**
   * Returns a readable version of {@link RewardDistributor} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
      stakePool: this.stakePool.toBase58(),
      authority: this.authority.toBase58(),
      rewardMint: this.rewardMint.toBase58(),
      rewardAmount: (() => {
        const x = <{ toNumber: () => number }>this.rewardAmount
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      rewardDurationSeconds: (() => {
        const x = <{ toNumber: () => number }>this.rewardDurationSeconds
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      rewardsIssued: (() => {
        const x = <{ toNumber: () => number }>this.rewardsIssued
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      multiplierDecimals: this.multiplierDecimals,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const rewardDistributorBeet = new beet.BeetStruct<
  RewardDistributor,
  RewardDistributorArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
    ['stakePool', beetSolana.publicKey],
    ['authority', beetSolana.publicKey],
    ['rewardMint', beetSolana.publicKey],
    ['rewardAmount', beet.u64],
    ['rewardDurationSeconds', beet.i128],
    ['rewardsIssued', beet.i128],
    ['multiplierDecimals', beet.u8],
  ],
  RewardDistributor.fromArgs,
  'RewardDistributor'
)
